name = "MecHom"
uuid = "5691c89d-90db-42bf-94d6-f5e5a83b8106"
authors = ["Robin Valmalette <valmalette@lma.cnrs-mrs.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
